backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    files: 
      - label: "Blog Post"
      - name: "blog"
      - file: content/blog/blog.json
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    preview_path: blog/{{slug}}
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  # - name: 'pages'
  #   label: 'Pages'
  #   files:
  #     - label: "Blog Post"
  #     - name: "blog_info"
  #     - file: content/posts/post.json
  #   fields:
  #       - { label: 'Phone', name: 'phone', widget: 'string' }
  #       - { label: 'Email', name: 'email', widget: 'string' }
  #       - { label: 'Address', name: 'address', widget: 'string' }