backend:
  name: git-gateway
  branch: publish-branch

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: "cms"
    label: "Indicium Tech CMS"
    description: "Indicium Tech CMS"
    files:
      - label: "Event Page"
        name: "Events"
        folder: "content/events/"
        file: "content/events/event.json"
        create: true
        fields:
          - label: "Event"
            name: "eventList"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: Details, name: details, widget: string }
              - { label: Date, name: date, widget: date }
              - { label: Place, name: place, widget: string }
              - { label: Participant 1, name: participants1, widget: string }
              - {
                  label: Participant 2,
                  name: participants2,
                  widget: string,
                  required: false,
                }
              - {
                  label: Participant 3,
                  name: participants3,
                  widget: string,
                  required: false,
                }
              - {
                  label: Participant 4,
                  name: participants4,
                  widget: string,
                  required: false,
                }
              - { label: Realization, name: realization, widget: string }
      - label: "Blog Page"
        name: "Blog"
        folder: "content/posts/"
        file: "content/posts/post.json"
        create: true
        fields:
          - label: "Blog Post"
            name: "blogList"
            widget: "list"
            fields:
              - { label: "title", name: "blog-title", widget: "string" }
              - { label: "image", name: "image", widget: "image" }
              - { label: Details, name: blog-description, widget: string }


